#!/bin/bash

usage() {
  echo "Usage: gitroot"
  exit 1
}

# $1: パス
# 与えられたパスがgitルートであるかどうか判定
is_git_root() {
  local -r dir=$1
  if [[ -d "$dir/.git" ]]; then
    return 0
  else
    return 1
  fi
}

main() {
  if [ $# -ne 0 ]; then
    usage
  fi
  
  local current_dir=$(pwd)
  
  # gitルートが見つかるまでディレクトリツリーを上にたどる
  while [[ $current_dir != "/" ]]; do
    if is_git_root $current_dir; then
      echo $current_dir
      exit 0
    fi
    current_dir=$(dirname $current_dir)
  done
  
  exit 1
}

main $@
