#!/bin/bash

usage() {
  echo "Usage: gitroot"
  exit 1
}

# $1: パス
# 与えられたパスがgitルートであるかどうか判定
is_git_root() {
  local -r dir=$1
  if [[ -d "$dir/.git" ]]; then
    return 0
  else
    return 1
  fi
}

if [ $# -ne 0 ]; then
  usage
fi

CURRENT_DIR=$(pwd)

# gitルートが見つかるまでディレクトリツリーを上にたどる
while [[ $CURRENT_DIR != "/" ]]; do
  if is_git_root $CURRENT_DIR; then
    echo $CURRENT_DIR
    exit 0
  fi
  CURRENT_DIR=$(dirname $CURRENT_DIR)
done

exit 1
